name: psychopy
channels:
- conda-forge
dependencies:
- python=3.7.3
- psychopy=3.1.5
- pip
- pandas=0.25
- numpy=1.16
- matplotlib=3.1
- seaborn=0.9
- pip:
  - psychtoolbox
  - pygame
  - pyglet==1.3.2
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"